services:
  - type: web
    name: webhook-line-notifier
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LINE_GROUP_ID
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
    healthCheckPath: /health